# pull official base image
FROM python:3.7.10-slim

# set work directory
# WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

# install psycopg2
# RUN apk update \
#     && apk add --virtual build-deps gcc python3-dev musl-dev \
#     && apk add postgresql-dev \
#     && pip install psycopg2 \
#     && apk del build-deps

# install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY /BAIron /BAIron
COPY /backend /backend
COPY /NLP /NLP

COPY manage.py .
COPY db.sqlite3 .
COPY .env .

COPY shakespeare_sonnets.txt .
COPY ginsberg.txt .
COPY cummings.txt .

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate
RUN python3 manage.py create_admin
RUN python3 manage.py save_poems

# add and run as non-root user
# RUN adduser -D myuser
# USER myuser

# run gunicorn
CMD gunicorn BAIron.wsgi:application --bind 0.0.0.0:$PORT