# Generated by Django 3.1.7 on 2021-05-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_line', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.input')),
            ],
        ),
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('name', models.CharField(choices=[('Plain', 'Plain'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Plain', 'Plain'), max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TuringTestVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.CharField(blank=True, max_length=200, null=True)),
                ('vote', models.CharField(choices=[('Human', 'Human'), ('Machine', 'Machine')], default='Machine', max_length=100)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.poem')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.poem')),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.poet'),
        ),
    ]
