# Generated by Django 3.1.7 on 2021-05-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Machine', 'Machine'), max_length=100)),
                ('first_line', models.CharField(max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Machine', 'Machine'), max_length=100)),
                ('text', models.CharField(default='', max_length=1000)),
                ('views', models.IntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.input')),
            ],
            options={
                'ordering': ('views',),
            },
        ),
        migrations.CreateModel(
            name='TuringTestVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', models.CharField(blank=True, max_length=200, null=True)),
                ('vote', models.CharField(choices=[('Human', 'Human'), ('Machine', 'Machine')], default='Machine', max_length=100)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.poem')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.poem')),
            ],
        ),
    ]
