# Generated by Django 3.1.7 on 2021-05-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='poet',
            field=models.CharField(choices=[('Plain', 'Plain'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Plain', 'Plain'), max_length=100),
        ),
        migrations.DeleteModel(
            name='Poet',
        ),
    ]
