# Generated by Django 3.1.7 on 2021-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='style',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Ginsberg', 'Ginsberg'), ('cummings', 'cummings')], default=('Machine', 'Machine'), max_length=100),
        ),
        migrations.AlterField(
            model_name='poem',
            name='author',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Ginsberg', 'Ginsberg'), ('cummings', 'cummings')], default=('Machine', 'Machine'), max_length=100),
        ),
    ]
