# Generated by Django 3.1.7 on 2021-05-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210503_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='sentiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
