# Generated by Django 3.1.7 on 2021-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210517_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='text',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
