# Generated by Django 3.1.7 on 2021-05-03 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_poem_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='poet',
        ),
        migrations.AddField(
            model_name='input',
            name='style',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Machine', 'Machine'), max_length=100),
        ),
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.CharField(choices=[('Machine', 'Machine'), ('Shakespeare', 'Shakespeare'), ('Cummings', 'Cummings'), ('Dickinson', 'Dickinson')], default=('Machine', 'Machine'), max_length=100),
        ),
        migrations.AlterField(
            model_name='poem',
            name='input',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.input'),
        ),
    ]
