# Generated by Django 3.1.7 on 2021-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211026_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='sentiment',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
