# Generated by Django 3.1.7 on 2021-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211026_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='generator_type',
            field=models.CharField(choices=[('Full', 'Full'), ('Collab', 'Collab')], default=('Full', 'Full'), max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='first_line',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
